Console.WriteLine("**** DateTime ****");
Console.WriteLine(DateTime.Now);
Console.WriteLine(DateTime.UtcNow);
Console.WriteLine(DateTime.Today);
Console.WriteLine(DateTime.DaysInMonth(2019, 2));
Console.WriteLine(DateTime.IsLeapYear(2019));
Console.WriteLine(DateTime.Now.AddDays(2));
Console.WriteLine(DateTime.Now.AddHours(2));
Console.WriteLine(DateTime.Now.AddMilliseconds(2));
Console.WriteLine(DateTime.Now.AddMonths(2));
Console.WriteLine(DateTime.Now.AddSeconds(2));
Console.WriteLine(DateTime.Now.AddYears(2));
Console.WriteLine(DateTime.Now.Day);
Console.WriteLine(DateTime.Now.DayOfWeek);
Console.WriteLine(DateTime.Now.DayOfYear);
Console.WriteLine(DateTime.Now.Hour);
Console.WriteLine(DateTime.Now.Millisecond);
Console.WriteLine(DateTime.Now.Minute);
Console.WriteLine(DateTime.Now.Month);
Console.WriteLine(DateTime.Now.Second);
Console.WriteLine(DateTime.Now.Ticks);
Console.WriteLine(DateTime.Now.TimeOfDay);
Console.WriteLine(DateTime.Now.Year);
Console.WriteLine(DateTime.Now.ToLongDateString());
Console.WriteLine(DateTime.Now.ToShortDateString());
Console.WriteLine(DateTime.Now.ToLongTimeString());
Console.WriteLine(DateTime.Now.ToShortTimeString());
Console.WriteLine(DateTime.Now.ToString("dd"));
Console.WriteLine(DateTime.Now.ToString("ddd"));
Console.WriteLine(DateTime.Now.ToString("dddd"));
Console.WriteLine(DateTime.Now.ToString("MM"));
Console.WriteLine(DateTime.Now.ToString("MMM"));
Console.WriteLine(DateTime.Now.ToString("MMMM"));
Console.WriteLine(DateTime.Now.ToString("yy"));
Console.WriteLine(DateTime.Now.ToString("yyyy"));
Console.WriteLine(DateTime.Now.ToString("hh"));
Console.WriteLine(DateTime.Now.ToString("HH"));
Console.WriteLine(DateTime.Now.ToString("mm"));
Console.WriteLine(DateTime.Now.ToString("ss"));
Console.WriteLine(DateTime.Now.ToString("tt"));
Console.WriteLine(DateTime.Now.ToString("fff"));
Console.WriteLine(DateTime.Now.ToString("dddd dd MMMM yyyy"));
Console.WriteLine(DateTime.Now.ToString("dddd dd MMMM yyyy HH:mm"));
Console.WriteLine(string.Format("{0:dddd dd MMMM yyyy HH:mm}", DateTime.Now));

Console.WriteLine("**** Math ****");
Console.WriteLine(Math.Abs(-25));
Console.WriteLine(Math.Ceiling(1.2));
Console.WriteLine(Math.Round(1.2));
Console.WriteLine(Math.Floor(1.2));
Console.WriteLine(Math.Max(1, 2));
Console.WriteLine(Math.Min(1, 2));
Console.WriteLine(Math.Pow(2, 3));
Console.WriteLine(Math.Sqrt(4));
Console.WriteLine(Math.Log(4));
Console.WriteLine(Math.Log10(4));
Console.WriteLine(Math.Exp(4));
Console.WriteLine(Math.Sin(4));
Console.WriteLine(Math.Cos(4));
Console.WriteLine(Math.Tan(4));
Console.WriteLine(Math.Cosh(4));
Console.WriteLine(Math.Sinh(4));
Console.WriteLine(Math.Tanh(4));
Console.WriteLine(Math.PI);
Console.WriteLine(Math.E);
